<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Dalamud.NET.Sdk/13.0.0">
	<PropertyGroup>
		<Authors>daemitus, croizat, Lother</Authors>
		<LangVersion>preview</LangVersion>
		<AppendPlatformToOutputPath>false</AppendPlatformToOutputPath>
		<DalamudLibPath>$(appdata)\FFXIVSimpleLauncher\Dalamud\Injector\</DalamudLibPath>
	</PropertyGroup>

	<PropertyGroup>
		<BuildNumberFile>$(MSBuildProjectDirectory)\BuildNumber.txt</BuildNumberFile>
		<_PreviousBuildNumber Condition="Exists('$(BuildNumberFile)')">$([System.IO.File]::ReadAllText('$(BuildNumberFile)').Trim())</_PreviousBuildNumber>
		<_PreviousBuildNumber Condition="'$(_PreviousBuildNumber)' == ''">0</_PreviousBuildNumber>
		<BuildNumber>$([MSBuild]::Add($(_PreviousBuildNumber), 1))</BuildNumber>
		<VersionPrefix>7.15.0</VersionPrefix>
		<Version>$(VersionPrefix).$(BuildNumber)</Version>
		<AssemblyVersion>$(Version)</AssemblyVersion>
		<FileVersion>$(Version)</FileVersion>
	</PropertyGroup>
	<Target Name="PersistBuildNumber" AfterTargets="Build">
		<WriteLinesToFile File="$(BuildNumberFile)" Lines="$(BuildNumber)" Overwrite="true" />
	</Target>

	<ItemGroup>
		<ProjectReference Include="..\ECommons\ECommons\ECommons.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="LanguageChineseTraditional.ini" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
</Project>